- name: install pip packages
  pip:
    executable: pip3
    name: 
    - prometheus_client
    - RPi.bme280
    - smbus2

- name: Transfer app.py
  template:
    src: app.j2
    dest: /home/pi/app.py
    owner: pi
    group: pi
    mode: 0755
  register: apppy