- name: install pip packages
  pip:
    executable: pip3
    name: 
    - pyserial
    - prometheus_client
    - bme680
    - smbus

- name: Transfer app.py
  template:
    src: app.j2
    dest: /home/pi/app.py
    owner: pi
    group: pi
    mode: 0755
  register: apppy